"""
Shared Agent Action Lifecycle Module
Artifact: agents/shared/lifecycle.py
Source: Chapter 11 — Agentic AI for Autonomous Patroni Operations

Implements the 6-state action lifecycle used by all AGENT-11-* scaffolds:
  observed → proposed → dry-run → approved → executed → verified

Every agent action MUST traverse these states. Approval can be:
  - automatic (for low-risk, read-only actions)
  - human-in-the-loop (for destructive actions: DDL, failover, slot drops)

Each state transition produces an immutable audit log entry.
"""

from __future__ import annotations

import json
import os
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum, auto
from pathlib import Path
from typing import Any, Callable, Literal


class AgentState(Enum):
    """The six states of the agent action lifecycle."""
    OBSERVED = auto()
    PROPOSED = auto()
    DRY_RUN = auto()
    APPROVED = auto()
    EXECUTED = auto()
    VERIFIED = auto()
    FAILED = auto()
    ROLLED_BACK = auto()


class ActionRisk(Enum):
    """Risk classification for approval routing."""
    LOW = "low"       # Read-only, monitoring, reporting
    MEDIUM = "medium" # Config changes with rollback path
    HIGH = "high"     # Destructive: DDL, failover, slot drops, cert rotation


@dataclass
class AuditEntry:
    """Immutable record of a single state transition."""
    action_id: str
    timestamp: str
    from_state: str
    to_state: str
    agent_id: str
    description: str
    context: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)


@dataclass
class ActionProposal:
    """Typed proposal generated by an agent before execution."""
    action_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    agent_id: str = ""
    description: str = ""
    risk_level: ActionRisk = ActionRisk.LOW
    target_cluster: str = ""
    proposed_action: str = ""
    proposed_params: dict[str, Any] = field(default_factory=dict)
    dry_run_result: dict[str, Any] | None = None
    manual_equivalent: str = ""
    # ^ MUST reference the manual runbook (Ch. 07 or Ch. 09 section)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["risk_level"] = self.risk_level.value
        return d


class AgentLifecycle:
    """
    Core lifecycle manager for all Patroni agent workflows.

    Usage:
        lifecycle = AgentLifecycle(agent_id="AGENT-11-MON")
        lifecycle.observe(signal="ALERT-06-LAG", context={...})
        proposal = lifecycle.propose(description="Correlate lag spike", action="notify", risk=ActionRisk.LOW)
        lifecycle.dry_run(proposal, dry_run_fn=lambda: simulate(proposal))
        if lifecycle.approve(proposal, auto_approve=True):
            lifecycle.execute(proposal, execute_fn=lambda: run(proposal))
            lifecycle.verify(proposal, verify_fn=lambda: check(proposal))
    """

    def __init__(
        self,
        agent_id: str,
        *,
        audit_log_path: str | None = None,
        auto_approve_low_risk: bool = True,
        require_human_approval_for: set[ActionRisk] | None = None,
    ) -> None:
        self.agent_id = agent_id
        self.audit_log_path = Path(audit_log_path or os.environ.get("AGENT_AUDIT_LOG", "./agent-audit.jsonl"))
        self.auto_approve_low_risk = auto_approve_low_risk
        self.require_human_approval_for = require_human_approval_for or {ActionRisk.HIGH}
        self._current_state: AgentState = AgentState.OBSERVED
        self._action_id: str | None = None

    # -----------------------------------------------------------------------
    # State transitions
    # -----------------------------------------------------------------------

    def observe(self, signal: str, context: dict[str, Any] | None = None) -> str:
        """Record that the agent observed a signal."""
        self._action_id = str(uuid.uuid4())
        self._current_state = AgentState.OBSERVED
        self._log(
            from_state="INIT",
            to_state=AgentState.OBSERVED.name,
            description=f"Observed signal: {signal}",
            context=context or {"signal": signal},
        )
        return self._action_id

    def propose(self, description: str, action: str, risk: ActionRisk, params: dict[str, Any] | None = None) -> ActionProposal:
        """Generate a typed action proposal."""
        if self._current_state != AgentState.OBSERVED:
            raise LifecycleError(f"Cannot propose from state {self._current_state.name}. Expected OBSERVED.")

        proposal = ActionProposal(
            action_id=self._action_id or str(uuid.uuid4()),
            agent_id=self.agent_id,
            description=description,
            risk_level=risk,
            proposed_action=action,
            proposed_params=params or {},
        )
        self._current_state = AgentState.PROPOSED
        self._log(
            from_state=AgentState.OBSERVED.name,
            to_state=AgentState.PROPOSED.name,
            description=f"Proposed action: {action} (risk={risk.value})",
            context=proposal.to_dict(),
        )
        return proposal

    def dry_run(self, proposal: ActionProposal, dry_run_fn: Callable[[], dict[str, Any]]) -> dict[str, Any]:
        """Execute the action in dry-run mode and capture the simulated result."""
        if self._current_state != AgentState.PROPOSED:
            raise LifecycleError(f"Cannot dry-run from state {self._current_state.name}. Expected PROPOSED.")

        result = dry_run_fn()
        proposal.dry_run_result = result
        self._current_state = AgentState.DRY_RUN
        self._log(
            from_state=AgentState.PROPOSED.name,
            to_state=AgentState.DRY_RUN.name,
            description=f"Dry-run of {proposal.proposed_action} completed",
            context={"dry_run_result": result},
        )
        return result

    def approve(self, proposal: ActionProposal, *, auto_approve: bool = False, human_confirmed: bool = False) -> bool:
        """
        Determine if the proposed action is approved for execution.

        Returns True if approved, False if rejected.
        """
        if self._current_state != AgentState.DRY_RUN:
            raise LifecycleError(f"Cannot approve from state {self._current_state.name}. Expected DRY_RUN.")

        # Guardrail: high-risk actions require human confirmation
        if proposal.risk_level in self.require_human_approval_for and not human_confirmed:
            self._current_state = AgentState.FAILED
            self._log(
                from_state=AgentState.DRY_RUN.name,
                to_state=AgentState.FAILED.name,
                description=f"Approval REJECTED: {proposal.proposed_action} requires human-in-the-loop (risk={proposal.risk_level.value})",
                context={"reason": "human_approval_required"},
            )
            return False

        # Guardrail: low-risk actions can auto-approve
        if proposal.risk_level == ActionRisk.LOW and self.auto_approve_low_risk and auto_approve:
            self._current_state = AgentState.APPROVED
            self._log(
                from_state=AgentState.DRY_RUN.name,
                to_state=AgentState.APPROVED.name,
                description=f"Auto-approved (low risk): {proposal.proposed_action}",
                context={"auto_approve": True},
            )
            return True

        # Medium risk: auto-approve if explicitly requested
        if proposal.risk_level == ActionRisk.MEDIUM and auto_approve:
            self._current_state = AgentState.APPROVED
            self._log(
                from_state=AgentState.DRY_RUN.name,
                to_state=AgentState.APPROVED.name,
                description=f"Auto-approved (medium risk): {proposal.proposed_action}",
                context={"auto_approve": True},
            )
            return True

        # Default: not approved
        self._current_state = AgentState.FAILED
        self._log(
            from_state=AgentState.DRY_RUN.name,
            to_state=AgentState.FAILED.name,
            description=f"Approval REJECTED: {proposal.proposed_action}",
            context={"reason": "not_approved"},
        )
        return False

    def execute(self, proposal: ActionProposal, execute_fn: Callable[[], dict[str, Any]]) -> dict[str, Any]:
        """Execute the approved action."""
        if self._current_state != AgentState.APPROVED:
            raise LifecycleError(f"Cannot execute from state {self._current_state.name}. Expected APPROVED.")

        result = execute_fn()
        self._current_state = AgentState.EXECUTED
        self._log(
            from_state=AgentState.APPROVED.name,
            to_state=AgentState.EXECUTED.name,
            description=f"Executed: {proposal.proposed_action}",
            context={"execution_result": result},
        )
        return result

    def verify(self, proposal: ActionProposal, verify_fn: Callable[[], dict[str, Any]]) -> dict[str, Any]:
        """Verify that the executed action resolved the original symptom."""
        if self._current_state != AgentState.EXECUTED:
            raise LifecycleError(f"Cannot verify from state {self._current_state.name}. Expected EXECUTED.")

        result = verify_fn()
        if result.get("success", False):
            self._current_state = AgentState.VERIFIED
            self._log(
                from_state=AgentState.EXECUTED.name,
                to_state=AgentState.VERIFIED.name,
                description=f"Verified: {proposal.proposed_action} resolved the issue",
                context={"verification_result": result},
            )
        else:
            self._current_state = AgentState.FAILED
            self._log(
                from_state=AgentState.EXECUTED.name,
                to_state=AgentState.FAILED.name,
                description=f"Verification FAILED: {proposal.proposed_action} did not resolve the issue",
                context={"verification_result": result, "reason": "verification_failed"},
            )
        return result

    # -----------------------------------------------------------------------
    # Audit logging
    # -----------------------------------------------------------------------

    def _log(self, *, from_state: str, to_state: str, description: str, context: dict[str, Any]) -> None:
        entry = AuditEntry(
            action_id=self._action_id or "unknown",
            timestamp=datetime.now(timezone.utc).isoformat(),
            from_state=from_state,
            to_state=to_state,
            agent_id=self.agent_id,
            description=description,
            context=context,
        )
        with open(self.audit_log_path, "a") as f:
            f.write(entry.to_json() + "\n")

    @property
    def current_state(self) -> AgentState:
        return self._current_state


class LifecycleError(Exception):
    """Raised when an invalid state transition is attempted."""
    pass


def require_dry_run_mode() -> None:
    """
    Enforce that the agent is running in dry-run mode by default.
    Call this at the entry point of every agent scaffold.

    The agent MUST be started with --dry-run or with the environment
    variable AGENT_DRY_RUN=true to execute safely.
    """
    dry_run = os.environ.get("AGENT_DRY_RUN", "true").lower() in ("true", "1", "yes")
    if not dry_run:
        print("=" * 60)
        print("WARNING: Agent is running in LIVE MODE (not dry-run)")
        print("Destructive actions WILL be executed.")
        print("Set AGENT_DRY_RUN=true to enable safe mode.")
        print("=" * 60)
        confirm = input("Type 'EXECUTE' to proceed in live mode: ")
        if confirm != "EXECUTE":
            print("Aborted. Set AGENT_DRY_RUN=true for dry-run mode.")
            exit(1)
